#!/bin/sh
set -e

IP=

usage()
{
	echo "Usage: docker-ssh <CONTAINER_ID> [COMMAND...]"
	echo "Login to a Baseimage-based Docker container using SSH." \
		"If COMMAND is not given, opens an interactive shell." \
		"Otherwise, runs COMMAND inside the container."
}

cleanup()
{
	local pids=`jobs -p`
	if test "$pids" != ""; then
		kill $pids
	fi
}

if test $# = 0; then
	usage
	exit
fi

CONTAINER_ID="$1"
shift

trap cleanup EXIT

IP=`docker inspect -f "{{ .NetworkSettings.IPAddress }}" "$CONTAINER_ID"`

if ! ssh \
	-o LogLevel=ERROR \
	-o GlobalKnownHostsFile=/dev/null \
	-o UserKnownHostsFile=/dev/null \
	-o StrictHostKeyChecking=no \
	-o BatchMode=yes \
	-o ConnectTimeout=3 \
	"root@$IP" "$@"
then
	STATUS=$?
	if test $# = 0; then
		echo "----------------"
		echo "It appears that login to the Docker container failed. This could be caused by the following reasons:"
		## TODO: we can automatically detect which is the problem, provide a better error message.
		echo "- The Docker container you're trying to login to is not based on Baseimage-docker. The docker-ssh tool only works with Baseimage-docker-based containers."
                echo "- You have no ssh-agent connection, or no keys added (to check, run: ssh-add -L)"
		echo '- You did not start the image with any authorized keys (--env=AUTHORIZED_KEYS="$(ssh-add -L)")'
		echo "- The image's sshd service is not started. Please read https://github.com/phusion/baseimage-docker/blob/master/README.md#login to learn how to enable the sshd service."
	fi
	exit $STATUS
fi
