#!/bin/sh
set -e

usage()
{
	echo "Usage: docker-bash <CONTAINER_ID> [COMMAND...]"
	echo "Login to a Baseimage-based Docker container using nsenter." \
		"If COMMAND is not given, opens an interactive shell." \
		"Otherwise, runs COMMAND inside the container."
}

if test $# = 0; then
	usage
	exit
fi

CONTAINER_ID="$1"
shift

PID=`docker inspect -f "{{ .State.Pid }}" "$CONTAINER_ID"`
if test $# = 0; then
	exec docker exec -ti "$CONTAINER_ID" "$@"
else
	exec docker exec -ti "$CONTAINER_ID" bash -l
fi

